### ISSUE TITLE
Chromium-specific bugs

### ISSUE THREAD

**Issue by Moscarda** [kevinsqi/save_tabbed_images#40]
Using this extension in several versions of Chromium built with flags set to higher security and privacy settings fails after downloading the first image.  I have also had this problem in official Chrome builds if my personal settings are configured similarly.

**Comment by iqnivek** [comment]
hmm, which settings specifically?

I'm not sure I can do anything about this, but I can take a quick look into it.

**Comment by kevinsqi** [comment]
Going to close this due to inactivity, but if you can provide more detail, feel free to re-open it. Thanks.
