### ISSUE TITLE
Save tabbed webm

### ISSUE THREAD

**Issue by blixnood** [kevinsqi/save_tabbed_images#44]
Feature request to also have it save tabbed webms.

**Comment by kevinsqi** [comment]
Seems reasonable to add. I haven't had much time to work on the extension unfortunately - PRs are welcome.

**Comment by blixnood** [comment]
I looked into it and it seems to be as simple as copy/pasting two lines for webm. I'll try to make a pull request now.

**Comment by kevinsqi** [comment]
Released as v0.7.0! I've published it to the Chrome web store - it's pending review.
